name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Library tests
        run: cargo test --no-default-features
      - name: Release GUI
        run: cargo build --release --features gui
